name: OakGlowUtil
main: com.tbfmc.tbfmp.TBFMPPlugin
version: 1.4.5
api-version: '1.21'
load: POSTWORLD
depend: [Vault]
commands:
  balance:
    aliases: [bal]
    description: Check your balance.
    usage: /<command> [player]
  balancetop:
    aliases: [baltop]
    description: View the top balances.
    usage: /<command>
  eco:
    description: Manage player balances.
    usage: /<command> <give|take|set> <player> <amount>
    permission: oakglowutil.admin.eco
  rtp:
    description: Start a one-time random teleport.
    usage: /<command>
  confirm:
    description: Confirm your one-time random teleport.
    usage: /<command>
  resetrtp:
    description: Reset a player's one-time RTP.
    usage: /<command> <player>
    permission: oakglowutil.admin.rtp
  pay:
    description: Pay another player.
    usage: /<command> <player> <amount>
  paytoggle:
    description: Toggle whether you can receive payments.
    usage: /<command>
  vote:
    description: Show the voting link.
    usage: /<command>
  web:
    description: Show the website link.
    usage: /<command>
  discord:
    description: Show the Discord link.
    usage: /<command>
  shoptut:
    description: Show the shop tutorial link.
    usage: /<command>
  rules:
    description: Show the rules link.
    usage: /<command>
  mallrules:
    description: Show the mall rules link.
    usage: /<command>
  hug:
    description: Send a hug to another player.
    usage: /<command> <player>
  oakglow:
    description: OakGlow administration command.
    usage: /<command> <reload|setspawn|dragondropset|convert|keepinvtoggle|pvptoggle|toggleleaderboard|resetevent|givehelpbook|sendonboarding>
  fly:
    description: Toggle flight in survival.
    usage: /<command>
  sit:
    description: Sit on the ground.
    usage: /<command>
  sitsetting:
    description: Toggle sit options.
    usage: /<command> <player|chair> <enable|disable>
  bank:
    description: Open the bank menu.
    usage: /<command>
  tags:
    description: Open the chat tag menu.
    usage: /<command>
  settings:
    description: Open the settings menu.
    usage: /<command>
  afk:
    description: Toggle AFK status.
    usage: /<command>
  event:
    description: Toggle the mining event scoreboard.
    usage: /<command> <show|hide>
  custom:
    description: Reload CustomConfig.yml.
    usage: /<command> reload
  mallwarp:
    description: Warp to the mall.
    usage: /<command>
  setmallwarp:
    description: Set the mall warp location.
    usage: /<command>
    permission: oakglowutil.admin.mallwarp
  setmallwarprg:
    description: Set the mall warp region.
    usage: /<command>
    permission: oakglowutil.admin.mallwarp
  backwarp:
    description: Return to your previous location before mall warp.
    usage: /<command>
  mc:
    description: Send a staff chat message.
    usage: /<command> <message>
    permission: oakglowutil.staffchat
  socialspy:
    aliases: [sspy]
    description: Toggle social spy.
    usage: /<command>
    permission: oakglowutil.admin.socialspy
  msg:
    aliases: [message]
    description: Send a private message.
    usage: /<command> <player> <message>
  mail:
    description: Send mail to offline players.
    usage: /<command> <send|read>
  tp:
    description: Teleport to a player or coordinates.
    usage: /<command> <player|x y z>
    permission: oakglowutil.admin.tp
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
    permission: oakglowutil.admin.tphere
  gamemode:
    aliases: [gm]
    description: Change your gamemode.
    usage: /<command> <survival|creative|spectator> [player]
  nick:
    description: Set your nickname.
    usage: /<command> <nickname|off>
    permission: oakglowutil.nick
  realname:
    description: Look up a player's real username from their nickname.
    usage: /<command> <nickname>
  unnick:
    description: Clear your nickname.
    usage: /<command>
    permission: oakglowutil.nick
  workbench:
    aliases: [wb, craft]
    description: Open a crafting table.
    usage: /<command>
    permission: oakglowutil.workbench
  enderchest:
    aliases: [ec]
    description: Open your ender chest.
    usage: /<command>
    permission: oakglowutil.enderchest
  ptime:
    description: Set your personal time.
    usage: /<command> <day|night|sunrise|sunset>
    permission: oakglowutil.ptime
  pweather:
    description: Set your personal weather.
    usage: /<command> <sun|rain|thunder>
    permission: oakglowutil.pweather
  playtime:
    description: Check or claim playtime rewards.
    usage: /<command> [player|claim]
  home:
    description: Teleport to one of your homes.
    usage: /<command> [name]
  homes:
    description: List your homes.
    usage: /<command>
  sethome:
    description: Set a home at your current location.
    usage: /<command> <name>
  warp:
    description: Teleport to a warp.
    usage: /<command> [name]
  warps:
    description: List warps.
    usage: /<command>
  setwarp:
    description: Set a warp at your current location.
    usage: /<command> <name>
    permission: oakglowutil.admin.setwarp
  back:
    description: Return to your previous location.
    usage: /<command>
  tpa:
    description: Request to teleport to a player.
    usage: /<command> <player>
  tpahere:
    description: Request a player teleport to you.
    usage: /<command> <player>
  tpaccept:
    description: Accept a teleport request.
    usage: /<command>
  tpdeny:
    description: Deny a teleport request.
    usage: /<command>
  tpatoggle:
    description: Toggle receiving teleport requests.
    usage: /<command>
permissions:
  oakglowutil.admin.eco:
    description: Allows use of /eco commands.
    default: op
  oakglowutil.admin.rtp:
    description: Allows use of /resetrtp.
    default: op
  oakglowutil.balance.others:
    description: Allows viewing other players' balances.
    default: op
  oakglowutil.admin.reload:
    description: Allows /oakglow reload.
    default: op
  oakglowutil.admin.setspawn:
    description: Allows /oakglow setspawn.
    default: op
  oakglowutil.admin.dragondropset:
    description: Allows /oakglow dragondropset.
    default: op
  oakglowutil.admin.convert:
    description: Allows /oakglow convert.
    default: op
  oakglowutil.admin.givehelpbook:
    description: Allows /oakglow givehelpbook.
    default: op
  oakglowutil.admin.sendonboarding:
    description: Allows /oakglow sendonboarding.
    default: op
  oakglowutil.admin.resetevent:
    description: Allows /oakglow resetevent.
    default: op
  oakglowutil.fly:
    description: Allows /fly in survival.
    default: op
  oakglowutil.admin.customreload:
    description: Allows /custom reload.
    default: op
  oakglowutil.admin.mallwarp:
    description: Allows setting the mall warp and region.
    default: op
  oakglowutil.staffchat:
    description: Allows using staff chat and viewing staff chat.
    default: op
  oakglowutil.admin.socialspy:
    description: Allows toggling social spy.
    default: op
  oakglowutil.admin.tp:
    description: Allows using /tp.
    default: op
  oakglowutil.admin.tphere:
    description: Allows using /tphere.
    default: op
  oakglowutil.gamemode.survival:
    description: Allows switching to survival mode.
    default: op
  oakglowutil.gamemode.creative:
    description: Allows switching to creative mode.
    default: op
  oakglowutil.gamemode.spectator:
    description: Allows switching to spectator mode.
    default: op
  oakglowutil.gamemode.others:
    description: Allows changing other players' gamemodes.
    default: op
  oakglowutil.nick:
    description: Allows use of /nick.
    default: op
  oakglowutil.workbench:
    description: Allows use of /workbench.
    default: op
  oakglowutil.enderchest:
    description: Allows use of /enderchest.
    default: op
  oakglowutil.ptime:
    description: Allows use of /ptime.
    default: op
  oakglowutil.pweather:
    description: Allows use of /pweather.
    default: op
  oakglowutil.playtime.others:
    description: Allows viewing other players' playtime.
    default: op
  oakglowutil.admin.setwarp:
    description: Allows setting warps with /setwarp.
    default: op
  critcolor.gold:
    description: Use gold critical hit particles.
    default: false
  critcolor.red:
    description: Use red critical hit particles.
    default: false
  critcolor.blue:
    description: Use blue critical hit particles.
    default: false
  crit.color.grey:
    description: Use grey critical hit particles.
    default: false
  crit.color.yellow:
    description: Use yellow critical hit particles.
    default: false
  crit.color.blue:
    description: Use blue critical hit particles.
    default: false
  crit.color.rainbow:
    description: Use rainbow critical hit particles.
    default: false
