name: TBFMP
main: com.tbfmc.tbfmp.TBFMPPlugin
version: 1.0.0
api-version: '1.21'
load: POSTWORLD
depend: [Vault]
commands:
  balance:
    aliases: [bal]
    description: Check your balance.
    usage: /<command> [player]
  balancetop:
    aliases: [baltop]
    description: View the top balances.
    usage: /<command>
  eco:
    description: Manage player balances.
    usage: /<command> <give|take|set> <player> <amount>
    permission: tbfmp.admin.eco
  rtp:
    description: Start a one-time random teleport.
    usage: /<command>
  confirm:
    description: Confirm your one-time random teleport.
    usage: /<command>
  resetrtp:
    description: Reset a player's one-time RTP.
    usage: /<command> <player>
    permission: tbfmp.admin.rtp
  pay:
    description: Pay another player.
    usage: /<command> <player> <amount>
  paytoggle:
    description: Toggle whether you can receive payments.
    usage: /<command>
  vote:
    description: Show the voting link.
    usage: /<command>
  web:
    description: Show the website link.
    usage: /<command>
  discord:
    description: Show the Discord link.
    usage: /<command>
  shoptut:
    description: Show the shop tutorial link.
    usage: /<command>
  hug:
    description: Send a hug to another player.
    usage: /<command> <player>
  tbfmc:
    description: TBFMC administration command.
    usage: /<command> <reload|setspawn>
  fly:
    description: Toggle flight in survival.
    usage: /<command>
  sit:
    description: Sit on the ground.
    usage: /<command>
  sitsetting:
    description: Toggle sit options.
    usage: /<command> <player|chair> <enable|disable>
  bank:
    description: Open the bank menu.
    usage: /<command>
  tags:
    description: Open the chat tag menu.
    usage: /<command>
  settings:
    description: Open the settings menu.
    usage: /<command>
  afk:
    description: Toggle AFK status.
    usage: /<command>
  invsee:
    description: View a player's inventory.
    usage: /<command> <player>
    permission: tbfmp.admin.invsee
  echestsee:
    description: View a player's ender chest.
    usage: /<command> <player>
    permission: tbfmp.admin.echestsee
permissions:
  tbfmp.admin.eco:
    description: Allows use of /eco commands.
    default: op
  tbfmp.admin.rtp:
    description: Allows use of /resetrtp.
    default: op
  tbfmp.balance.others:
    description: Allows viewing other players' balances.
    default: op
  tbfmp.admin.reload:
    description: Allows /tbfmc reload.
    default: op
  tbfmp.admin.setspawn:
    description: Allows /tbfmc setspawn.
    default: op
  tbfmp.fly:
    description: Allows /fly in survival.
    default: op
  tbfmp.admin.invsee:
    description: Allows /invsee.
    default: op
  tbfmp.admin.echestsee:
    description: Allows /echestsee.
    default: op
  critcolor.gold:
    description: Use gold critical hit particles.
    default: false
  critcolor.red:
    description: Use red critical hit particles.
    default: false
  critcolor.blue:
    description: Use blue critical hit particles.
    default: false
